<a href="https://colab.research.google.com/github/dineshv9042/1.-Slab-1--i-/blob/main/1_Slab_1_(iii).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
rows1 = int(input("Enter number of rows for Matrix A: "))
cols1 = int(input("Enter number of columns for Matrix A: "))

A = np.zeros((rows1, cols1))

print("Enter elements of Matrix A:")

for i in range(rows1):
    for j in range(cols1):
        A[i][j] = float(input(f"A[{i+1}][{j+1}]: "))

print("\nMatrix A:")
print(A)

Enter number of rows for Matrix A: 2
Enter number of columns for Matrix A: 2
Enter elements of Matrix A:
A[1][1]: 1
A[1][2]: 2
A[2][1]: 3
A[2][2]: 4

Matrix A:
[[1. 2.]
 [3. 4.]]


In [ ]:
rows2 = int(input("Enter number of rows for Matrix B: "))
cols2 = int(input("Enter number of columns for Matrix B: "))

B = np.zeros((rows2, cols2))

print("Enter elements of Matrix B:")

for i in range(rows2):
    for j in range(cols2):
        B[i][j] = float(input(f"B[{i+1}][{j+1}]: "))

print("\nMatrix B:")
print(B)

Enter number of rows for Matrix B: 2
Enter number of columns for Matrix B: 2
Enter elements of Matrix B:
B[1][1]: 5
B[1][2]: 6
B[2][1]: 7
B[2][2]: 8

Matrix B:
[[5. 6.]
 [7. 8.]]


In [ ]:
if A.shape == B.shape:
    addition = A + B

    print("Matrix A:")
    print(A)

    print("\nMatrix B:")
    print(B)

    print("\nA + B:")
    print(addition)
else:
    print("Error: Both matrices must have the same dimensions.")

Matrix A:
[[1. 2.]
 [3. 4.]]

Matrix B:
[[5. 6.]
 [7. 8.]]

A + B:
[[ 6.  8.]
 [10. 12.]]


In [ ]:
if A.shape == B.shape:
    subtraction = A - B

    print("Matrix A:")
    print(A)

    print("\nMatrix B:")
    print(B)

    print("\nA - B:")
    print(subtraction)
else:
    print("Error: Both matrices must have the same dimensions.")

Matrix A:
[[1. 2.]
 [3. 4.]]

Matrix B:
[[5. 6.]
 [7. 8.]]

A - B:
[[-4. -4.]
 [-4. -4.]]


In [ ]:
if cols1 == rows2:
    multiplication = np.matmul(A, B)

    print("Matrix A:")
    print(A)

    print("\nMatrix B:")
    print(B)

    print("\nA × B:")
    print(multiplication)
else:
    print("Error: Columns of Matrix A must equal rows of Matrix B.")

Matrix A:
[[1. 2.]
 [3. 4.]]

Matrix B:
[[5. 6.]
 [7. 8.]]

A × B:
[[19. 22.]
 [43. 50.]]


In [ ]:
transpose_A = A.T

print("Matrix A:")
print(A)

print("\nTranspose of A:")
print(transpose_A)

Matrix A:
[[1. 2.]
 [3. 4.]]

Transpose of A:
[[1. 3.]
 [2. 4.]]


In [ ]:
transpose_B = B.T

print("Matrix B:")
print(B)

print("\nTranspose of B:")
print(transpose_B)

Matrix B:
[[5. 6.]
 [7. 8.]]

Transpose of B:
[[5. 7.]
 [6. 8.]]


In [ ]:
if rows1 == cols1:
    determinant_A = np.linalg.det(A)

    print("Matrix A:")
    print(A)

    print("\nDeterminant of A:", round(determinant_A, 2))
else:
    print("Error: Determinant can only be calculated for a square matrix.")

Matrix A:
[[1. 2.]
 [3. 4.]]

Determinant of A: -2.0


In [ ]:
if rows2 == cols2:
    determinant_B = np.linalg.det(B)

    print("Matrix B:")
    print(B)

    print("\nDeterminant of B:", round(determinant_B, 2))
else:
    print("Error: Determinant can only be calculated for a square matrix.")

Matrix B:
[[5. 6.]
 [7. 8.]]

Determinant of B: -2.0
